// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbJmghc-FhrUAJ1BCBQP7vcilZ3K108c8',
    appId: '1:1024129936644:web:f622dab37584993ac53451',
    messagingSenderId: '1024129936644',
    projectId: 'linux-phone-store',
    authDomain: 'linux-phone-store.firebaseapp.com',
    storageBucket: 'linux-phone-store.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxinTP-WzH_r_8TiJQFrnDGvx41oNaeGQ',
    appId: '1:1024129936644:android:e5893c4f0503b4d9c53451',
    messagingSenderId: '1024129936644',
    projectId: 'linux-phone-store',
    storageBucket: 'linux-phone-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQytqMNTRHIfXogCB5jV--VjMFGG6tIwE',
    appId: '1:1024129936644:ios:50268dc954e58458c53451',
    messagingSenderId: '1024129936644',
    projectId: 'linux-phone-store',
    storageBucket: 'linux-phone-store.appspot.com',
    iosBundleId: 'com.example.phoneStoreLinux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQytqMNTRHIfXogCB5jV--VjMFGG6tIwE',
    appId: '1:1024129936644:ios:73728aea917e6e23c53451',
    messagingSenderId: '1024129936644',
    projectId: 'linux-phone-store',
    storageBucket: 'linux-phone-store.appspot.com',
    iosBundleId: 'com.example.phoneStoreLinux.RunnerTests',
  );
}
